apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-demo
  template:
    metadata:
      labels:
        app: react-demo
    spec:
      containers:
        - name: react-demo
          image: gcr.io/onus-sandbox/react-demo:v1.0.4
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/postStart.sh"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "echo Hello from the preStop handler > /usr/share/message"]
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            timeoutSeconds: 4 
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: "50m"
              memory: "0.2Gi"
            limits:
              cpu: "100m"
              memory: "0.5Gi"
          env:
          - name: MY_POD_IP 
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace