name: Build and Push Frontend Image to GCR 
on:
  push:
    branches: [main]

env:
  IMAGE_NAME: gcr.io/onus-sandbox/react-demo
  PROJECT_ID: onus-sandbox
  GKE_ZONE: asia-southeast1-b
  GKE_CLUSTER: sandbox-gke

jobs:
  build-push-gcr:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SANDBOX_SA }}'

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0
    
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Declare some variables
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn' # or yarn
    
    - name: Setup yarn
      run: yarn install
    
    - name: Build source
      run: yarn build

    - name: Build docker image
      run: docker build . -t $IMAGE_NAME:latest

    - name: Push Image to Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ steps.vars.outputs.sha_short }}
    
    outputs:
      GIT_TAG: ${{ steps.vars.outputs.sha_short }}
# Deploy to GKE
  deploy-to-gke:
    runs-on: ubuntu-latest
    needs: build-push-gcr
    
    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SANDBOX_SA }}'

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0
    
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.SANDBOX_SA }}
    
    # Deploy the new Docker image to GKE cluster
    - name: Deploy
      env:
        IMAGE_TAG: ${{ needs.build-push-gcr.outputs.GIT_TAG }}
      run: |-
        echo $IMAGE_TAG
        kubectl set image deployment react-demo react-demo=$IMAGE_NAME:$IMAGE_TAG